name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
    - name: Set up Java and Scala
      uses: coursier/setup-action@v1
      with:
        jvm: graalvm-community:17.0.9
    - uses: actions/setup-node@v3
    - name: NPM Install
      run: npm install
    - name: Compile, Test, Format check
      run: sbt clean test scalafmtCheckAll scalafmtSbtCheck "scalafixAll --check"
