name: release
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Java and Scala
        uses: coursier/setup-action@v1
        with:
          java-version: graalvm-java17:22.3.3
      - name: Publish
        run: sbt dist
